package:
  name: sqlalchemy-migrate
  version: "0.9.7"

source:
  fn: sqlalchemy-migrate-0.9.7.tar.gz
  url: https://pypi.python.org/packages/source/s/sqlalchemy-migrate/sqlalchemy-migrate-0.9.7.tar.gz
  md5: fd586f77b25f905d56d1847fc1f9c68b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - migrate = migrate.versioning.shell:main
    - migrate-repository = migrate.versioning.migrate_repository:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3

  run:
    - python
    - "sqlalchemy >=0.7.8,!=0.9.5"
    - six >=1.7.0
    - decorator
    - sqlparse
    - tempita >-0.4

test:
  # Python imports
  # imports:

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - migrate --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'Database schema migration for SQLAlchemy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
